name: Pipe Playwright

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

  schedule:
  - cron: "0 12,20 * * 1-5"

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Eslint verify
        run: npx eslint src  
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: npm run test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30  
